name: flutter_gpu_filters_interface
description: Multi platform interfaces for filters based on OpenGL shaders and Apple CoreImage filters
version: 0.0.18
homepage: https://github.com/nikolaydymura/flutter_gpu_filters_interface
repository: https://github.com/nikolaydymura/flutter_gpu_filters_interface

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
